apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    field.cattle.io/creatorId: u-liao
  name: redis-liao-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      annotations:      
        field.cattle.io/ports: '[[{"containerPort":6379,"dnsName":"redis-nodeport","kind":"NodePort","name":"6379tcp10361","protocol":"TCP","sourcePort":10361}]]'      
      labels:
        app: redis
    spec:
      containers:
      - name: redisx
        image: 192.168.3.207:5000/fft/redis:v1.4
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  selector:
    app: redis
  type: NodePort
  ports:
  - name: tcp
    nodePort: 10361
    port: 6379
    protocol: TCP
    targetPort: 6379