apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-liao-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        track: stable
    spec:
      containers:
      - name: redis
        image: 192.168.3.207:5000/fft/redis:v1.2
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379